### ISSUE TITLE
Device not Found (udevadm)

### ISSUE THREAD

**Issue by ghost** [StefanSchoof/volkszaehler.org-config#2]
Hallo Stefan,

ich habe per udevadm ein Link eingerichtet, damit ich 2 Leseköpfe eindeutig zuordnen kann.

cat /dev/ttyUSB0 und auch der Link cat /dev/ttyUSBZ1 liefern Ergebnisse.

Wenn ich in der vzlogger.conf /dev/ttyUSB0 angebe klappt alles wunderbar.
Wenn ich aber /dev/ttyUSBZ1 als device angebe kommt der Fehler:

open(/dev/ttyUSBZ1): No such file or directory

Hast du eine Idee?

**Comment by StefanSchoof** [comment]
Hast du ` /dev/ttyUSBZ1` als device im docker container gemounted?

https://github.com/StefanSchoof/volkszaehler.org-config/blob/879aa74aaf6694180b5ee47d2faeea12030bdb5b/docker-compose.yml#L45-L46

**Comment by ghost** [comment]
Ich habe auf meiner Synology den Container mit hoher Priorität gestartet. 
Damit sollte doch alles durchgereicht werden, oder?

![image](https://github.com/StefanSchoof/volkszaehler.org-config/assets/18594343/303e919d-c651-4546-a16e-a2eccec782ba)

**Comment by StefanSchoof** [comment]
Ich habe keine Ahnung von Synology docker.

**Comment by ghost** [comment]
Er hat das Gerät tatsächlich nicht durchgereicht. Mit dem Mapping, wie von dir beschrieben, hat es geklappt. Danke,
